/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Bike entity.
 *
 * @author yann39
 * @since 1.0.0
 */
@Getter
@Setter
@Entity
@Table(name = "bike")
public class Bike {

    /**
     * Database identifier (primary key) for this bike.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The bike manufacturer, maximum 64 characters.
     */
    @Column(length = 64, nullable = false)
    private String manufacturer;

    /**
     * The bike model name, maximum 128 characters.
     */
    @Column(length = 128, nullable = false)
    private String modelName;

    /**
     * The bike engine size, in cubic centimeters (cc).
     */
    @Column
    private Integer engineSize;

    /**
     * The bike year of manufacture.
     */
    @Column
    private Integer year;

    /**
     * To identify if the bike is the member's current main bike.
     */
    @Column(nullable = false)
    private Boolean current = false;

    /**
     * The bike's owner.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id")
    private Member member;

}
