/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.List;

/**
 * Circuit (venue) entity. Holds the identity shared by every layout / version of a physical
 * circuit (name, country, GPS, website). The raceable unit — the one lap records and events
 * reference — remains the {@link Track}, which now represents a single version of a circuit.
 *
 * @author yann39
 * @since 1.3.0
 */
@Getter
@Setter
@Entity
@Table(name = "circuit")
public class Circuit {

    /**
     * Database identifier (primary key) for this circuit.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Circuit (venue) name, maximum 128 characters (e.g. "Circuit Paul Ricard").
     */
    @Column(length = 128, nullable = false)
    private String name;

    /**
     * Country where the circuit is located. References Country.code (ISO 3166-1 alpha-2).
     * <p>
     * Fetched eagerly so it resolves everywhere a circuit is serialized without open-session-in-view.
     */
    @ManyToOne(optional = false)
    @JoinColumn(name = "country_code", nullable = false)
    private Country country;

    /**
     * Latitude coordinate of the circuit location.
     * <p>
     * Stored with precision suitable for geographic coordinates.
     */
    @Column(precision = 10, scale = 8)
    private BigDecimal latitude;

    /**
     * Longitude coordinate of the circuit location.
     */
    @Column(precision = 11, scale = 8)
    private BigDecimal longitude;

    /**
     * Circuit website link, max 2048 characters.
     */
    @Column(length = 2048)
    private String website;

    /**
     * Versions (layouts) available on this circuit. Lazily loaded; the circuit read queries
     * fetch it explicitly when the tracks are needed.
     */
    @OneToMany(mappedBy = "circuit", fetch = FetchType.LAZY)
    @OrderBy("variantName")
    private List<Track> tracks;

}
