/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * A single track session of an {@link Event}, e.g. one 20-minute run.
 * <p>
 * The schedule is entered by an admin as groups ("5 sessions of 20 min, then 1 of 25 min") but stored flat,
 * one row per session, so that a participant can tick the individual sessions they actually rode
 * (see {@link EventMember#getSkippedSessions()}).
 *
 * @author yann39
 * @since 1.2.2
 */
@Getter
@Setter
@Entity
@Table(name = "event_session")
public class EventSession implements Comparable<EventSession> {

    /**
     * Database identifier (primary key) for this session.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Event this session belongs to.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "event_id", nullable = false)
    private Event event;

    /**
     * 1-based rank of the session within the event day, used to keep the schedule ordered
     * and to label the session in the UI ("session 3").
     */
    @Column(nullable = false)
    private Integer position;

    /**
     * Duration of the session, in minutes.
     */
    @Column(name = "duration_minutes", nullable = false)
    private Integer durationMinutes;

    /**
     * Order sessions by their rank in the day, so the schedule reads in order wherever it is iterated.
     * <p>
     * {@link Event} holds them in a sorted set, which drops elements that compare equal, hence the fallback
     * on the id: positions are unique within an event, but two not-yet-persisted sessions must still be
     * distinguishable while the schedule is being built.
     */
    @Override
    public int compareTo(EventSession other) {
        final int byPosition = Integer.compare(
                position != null ? position : Integer.MAX_VALUE,
                other.position != null ? other.position : Integer.MAX_VALUE);
        if (byPosition != 0) {
            return byPosition;
        }
        if (this == other) {
            return 0;
        }
        return Long.compare(
                id != null ? id : Long.MAX_VALUE,
                other.id != null ? other.id : Long.MAX_VALUE);
    }

}
