/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * @author yann39
 * @since 1.0.0
 */
@Getter
@Setter
@Entity
@Table(name = "lap_record")
public class LapRecord {

    /**
     * Database identifier (primary key) for this lap record.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Track where the lap was recorded.
     */
    @ManyToOne
    @JoinColumn(name = "track_id")
    private Track track;

    /**
     * Member who recorded the lap.
     */
    @ManyToOne
    @JoinColumn(name = "member_id")
    private Member member;

    /**
     * Bike used to record the lap.
     */
    @ManyToOne
    @JoinColumn(name = "bike_id")
    private Bike bike;

    /**
     * Lap time in milliseconds.
     */
    @Column(nullable = false)
    private int lapTime;

    /**
     * Date and time when the lap record was set.
     */
    @Column(nullable = false)
    private LocalDateTime recordDate;

    /**
     * Conditions during the lap (weather).
     */
    @Column(length = 32, nullable = false)
    private String conditions;

    /**
     * Optional comments about the lap record.
     */
    @Column(columnDefinition = "longtext")
    private String comments;

    /**
     * Creation timestamp for the lap record.
     */
    @Column(nullable = false)
    private LocalDateTime createdOn = LocalDateTime.now();

    /**
     * Last modification timestamp for the lap record.
     */
    @Column
    private LocalDateTime modifiedOn;

}
