/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * MembershipFee entity.
 *
 * @author yann39
 * @since 1.0.0
 */
@Getter
@Setter
@Entity
@Table(name = "membership_fee", uniqueConstraints = {
        @UniqueConstraint(columnNames = {"member_id", "year"})
})
public class MembershipFee {

    /**
     * Database identifier (primary key) for this membership fees.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Member who paid the fee.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id", nullable = false)
    private Member member;

    /**
     * Year for which the membership fee applies.
     */
    @Column(nullable = false)
    private Integer year;

    /**
     * Amount of the membership fee.
     */
    @Column(nullable = false)
    private Float amount;

    /**
     * Whether the fee has been paid.
     */
    @Column(nullable = false)
    private boolean paid = false;

    /**
     * Creation timestamp for the membership fee record.
     */
    @Column(nullable = false)
    private LocalDateTime createdOn = LocalDateTime.now();

    /**
     * Last modification timestamp for the fee record.
     */
    @Column
    private LocalDateTime modifiedOn;

}
