/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import com.ccteam.graphql.enums.BoardRole;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.security.core.GrantedAuthority;

import java.time.LocalDateTime;
import java.util.Set;

/**
 * @author yann39
 * @since 1.0.0
 */
@Getter
@Setter
@Entity
@Table(name = "member")
public class Member {

    /**
     * Database identifier (primary key) for this member.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Member's first name.
     */
    @Column(length = 64, nullable = false)
    private String firstName;

    /**
     * Member's last name.
     */
    @Column(length = 64, nullable = false)
    private String lastName;

    /**
     * Unique email address used as login identifier.
     */
    @Column(length = 128, nullable = false, unique = true)
    private String email;

    /**
     * Hashed password (may be null for OAuth-only accounts).
     */
    @Column
    private String password;

    /**
     * Phone number in international format without separators.
     */
    @Column(length = 13)
    private String phone;

    /**
     * Optional avatar attachment for the member.
     */
    @OneToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    @JoinColumn(name = "attachment_id")
    private Attachment avatar;

    /**
     * Racing rider number assigned to the member (nullable).
     */
    @Column
    private Integer riderNumber;

    /**
     * Optional UI header palette selection for the member profile.
     */
    @Column(name = "header_palette")
    private Integer headerPalette;

    /**
     * Bikes owned by the member.
     */
    @OneToMany(mappedBy = "member", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("manufacturer ASC, modelName ASC")
    private Set<Bike> bikes;

    /**
     * Membership fees records associated with the member.
     */
    @OneToMany(mappedBy = "member", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<MembershipFee> membershipFees;

    /**
     * Whether the member's email has been verified.
     */
    @Column(nullable = false)
    private boolean verified = false;

    /**
     * Last OTP sent to the member (if any).
     */
    @Column
    private String otp;

    /**
     * Timestamp when the last OTP was issued.
     */
    @Column
    private LocalDateTime otpDate;

    /**
     * Member's role in the application security model.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role;

    /**
     * Optional board role (if the member sits on the board).
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "board_role")
    private BoardRole boardRole;

    /**
     * Date when the member registered.
     */
    @Column
    private LocalDateTime registrationDate;

    /**
     * Count of consecutive failed login attempts.
     */
    @Column(name = "failed_login_attempts", nullable = false)
    private int failedLoginAttempts = 0;

    /**
     * If present, account is locked until this timestamp.
     */
    @Column(name = "locked_until")
    private LocalDateTime lockedUntil;

    /**
     * News items liked by the member.
     */
    @OneToMany(mappedBy = "member", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<LikedNews> likedNews;

    /**
     * Event registrations for the member.
     */
    @OneToMany(mappedBy = "member", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<EventMember> eventMembers;

    /**
     * Account creation timestamp.
     */
    @Column(nullable = false)
    private LocalDateTime createdOn = LocalDateTime.now();

    /**
     * Last modification timestamp for the member profile.
     */
    @Column
    private LocalDateTime modifiedOn;

    public enum Role implements GrantedAuthority {
        ROLE_USER,
        ROLE_MEMBER,
        ROLE_ADMIN;

        @Override
        public String getAuthority() {
            return this.name();
        }
    }

}
