/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.Set;

/**
 * @author yann39
 * @since 1.0.0
 */
@Getter
@Setter
@Entity
@Table(name = "news")
public class News {

    /**
     * Database identifier (primary key) for this news item.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the news item.
     */
    @Column(length = 128, nullable = false)
    private String title;

    /**
     * Short summary or catch line displayed in lists.
     */
    @Column(columnDefinition = "longtext", length = 512, nullable = false)
    private String catchLine;

    /**
     * Full content of the news item (may include HTML or markdown), maximum 64KB.
     */
    @Column(length = 65535, nullable = false)
    private String content;

    /**
     * Date when the news item applies or was published.
     */
    @Column(nullable = false)
    private LocalDateTime newsDate;

    /**
     * Likes associated with this news item.
     */
    @OneToMany(mappedBy = "news", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<LikedNews> likedNews;

    /**
     * Creation timestamp of the news item.
     */
    @Column(nullable = false)
    private LocalDateTime createdOn = LocalDateTime.now();

    /**
     * Member who created the news item.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "created_by")
    private Member createdBy;

    /**
     * Last modification timestamp.
     */
    @Column
    private LocalDateTime modifiedOn;

    /**
     * Member who last modified the news item.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "modified_by")
    private Member modifiedBy;

}
