/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

/**
 * @author yann39
 * @since 1.0.0
 */
@Getter
@Setter
@Entity
@Table(name = "otp")
public class Otp {

    /**
     * Database identifier (primary key) for this OTP entry.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Email address associated with this OTP.
     */
    @Column(length = 128, nullable = false)
    private String email;

    /**
     * One-time password (OTP) value.
     */
    @Column
    private String otp;

    /**
     * Date and time when the OTP was generated or is valid until.
     */
    @Column
    private LocalDateTime otpDate;

    /**
     * Number of verification attempts for this OTP.
     */
    @Column
    private int attempts;

    /**
     * Creation timestamp of the OTP entry.
     */
    @Column(nullable = false)
    private LocalDateTime createdOn = LocalDateTime.now();

}
