/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

/**
 * Track entity, a single version (layout) of a {@link Circuit}.
 *
 * @author yann39
 * @since 1.0.0
 */
@Getter
@Setter
@Entity
@Table(name = "track")
public class Track {

    /**
     * Database identifier (primary key) for this track.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Circuit (venue) this version belongs to.
     * <p>
     * Fetched eagerly so {@code track.circuit} (and, through it, the country) resolves everywhere a
     * track is serialized without open-session-in-view, mirroring how {@code event.track} is loaded.
     * <p>
     * The join column is left nullable at the entity level so the schema migration can add it to the
     * populated {@code track} table; it is enforced non-null by {@code TrackService} and tightened at
     * the database level once every row has been linked to a circuit.
     */
    @ManyToOne
    @JoinColumn(name = "circuit_id")
    private Circuit circuit;

    /**
     * Version / layout label within the circuit (e.g. "5,8 km GP", "3,8 km", "Sens inversé").
     * Null or blank when the circuit has a single version.
     */
    @Column(length = 128)
    private String variantName;

    /**
     * Track length in meters (specific to this version).
     */
    @Column
    private int distance;

    /**
     * Best lap time recorded on this version (expressed in milliseconds).
     */
    @Column
    private int lapRecord;

    /**
     * Additional information about the lap record (rider name, bike, date, ...).
     */
    @Column
    private String lapRecordInfo;

    /**
     * Key selecting the small map/shape icon for this version (font-icon lookup on the client).
     * Null falls back to the circuit's default icon.
     */
    @Column(length = 64)
    private String iconKey;

}
