/*
 * Copyright (c) 2024 by Yann39
 *
 * This file is part of CCTeam GraphQL application.
 *
 * CCTeam GraphQL is free software: you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * CCTeam GraphQL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with CCTeam GraphQL. If not, see <http://www.gnu.org/licenses/>.
 *
 */

package com.ccteam.graphql.entities;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * @author yann39
 * @since 1.0.0
 */
@Getter
@Setter
@Entity
@Table(name = "track")
public class Track {

    /**
     * Database identifier (primary key) for this track.
     * <p>
     * Generated by the database when the entity is persisted.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Track name, maximum 128 characters.
     */
    @Column(length = 128, nullable = false)
    private String name;

    /**
     * Track length in meters.
     */
    @Column
    private int distance;

    /**
     * Best lap time recorded on this track (expressed in milliseconds).
     */
    @Column
    private int lapRecord;

    /**
     * Additional information about the lap record (rider name, bike, date, ...).
     */
    @Column
    private String lapRecordInfo;

    /**
     * Track website link, max 2048 characters.
     */
    @Column(length = 2048)
    private String website;

    /**
     * Latitude coordinate of the track location.
     * <p>
     * Stored with precision suitable for geographic coordinates.
     */
    @Column(precision = 10, scale = 8)
    private BigDecimal latitude;

    /**
     * Longitude coordinate of the track location.
     */
    @Column(precision = 11, scale = 8)
    private BigDecimal longitude;

    /**
     * Country where the track is located. References Country.code (ISO 3166-1 alpha-2).
     */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "country_code", nullable = false)
    private Country country;

}
